spring:
  application:
    name: jobs-service

mongohost: localhost

server:
  port: 1114

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5