# Registration Server config
spring:
  application:
    name: appointment-service


server:
  port: 1114  # Registration server port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5