spring:
  application:
    name: technician-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost

server:
  port: 1115