# User server config
spring:
  application:
    name: user-service

# Registration Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 2222   # User server port