server:
  port: 1113

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CarService
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5