spring:
  application:
    name: jobs-service

mongohost: mongod

server:
  port: 1114

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5