server:
  port: 1113

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: mongod
      port: 27017
      database: CarService

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5