spring:
  application:
    name: car-service


server:
  port: 1115  # Registration server port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5