server:
  port: 1116

spring:
  application:
    name: report-service
  data:
    mongodb:
      port: 27017
      host: mongod
      database: CarService

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5