server:
    port: 1116

spring:
  application:
    name: reports-service
  data:
    mongodb:
      port: 27017
      host: localhost
      database: CarService

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
